### ISSUE TITLE
Add Travis or Circle integration

### ISSUE THREAD

**Issue by pierceray** [wellington/grunt-wellington#14]
Setup Travis CI integration

**Comment by pierceray** [comment]
I don't have admin rights to setup either of projects.  @drewwells

**Comment by drewwells** [comment]
@pierceray try now

**Comment by pierceray** [comment]
Nope.

![image](https://cloud.githubusercontent.com/assets/738033/18901778/8f208568-8513-11e6-97bc-83a0008da4e0.png)

**Comment by drewwells** [comment]
it's turned on now

**Comment by pierceray** [comment]
Looks like we are good to go and builds are green.
