### ISSUE TITLE
Document the different configuration options

### ISSUE THREAD

**Issue by pierceray** [wellington/grunt-wellington#7]
Currently there is no documentation in the grunt-wellington project about what options are available to be passed to the compiler via the `Gruntfile.js`.  I created wellington/wellington#142 because I couldn't locate the info Wellington either.  We shouldn't we using the terse single character config options by default in grunt-wellington, a new user would have no context as to what they meant.

**Comment by drewwells** [comment]
The available cli subcommands and args are now listed on the readme: https://github.com/wellington/wellington#available-commands
